- id: '1547180897200'
  alias: Sunset - Turn On Outdoor Lights
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data:
      entity_id: group.outdoor_lights
    service: switch.turn_on
- id: '1547235814708'
  alias: Nighttime - Turn off Outdoor Lights
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_off
- id: '1547241126929'
  alias: Everyones home
  trigger:
  - entity_id: group.adults
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_off
- id: '1547328859557'
  alias: Someone left after dark
  trigger:
  - entity_id: group.adults
    event: leave
    platform: zone
    zone: zone.home
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_on
- id: '1547432270277'
  alias: Workday Mornings - Turn on Kitchen Light
  trigger:
  - at: 05:30:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.ge_14291_inwall_smart_switch_switch
    service: switch.turn_on
- id: '1547433263483'
  alias: Workday Mornings - Turn on Outdoor Lights
  trigger:
  - at: 06:20
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - before: sunrise
    condition: sun
  action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_on
- id: '1547434549041'
  alias: Sunrise - Turn Off Outdoor Lights
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: group.outdoor_lights
    service: switch.turn_off
- id: '1547435118208'
  alias: Workday Mornings - Turn off Kitchen Light
  trigger:
  - at: 08:20:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.ge_14291_inwall_smart_switch_switch
    service: switch.turn_off
