- id: '1547180897200'
  alias: Sunset - Turn On Outdoor Lights
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: group.adults
    state: not_home
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.outdoor_lights
- id: '1547235814708'
  alias: Nighttime - Turn off Outdoor Lights
  trigger:
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id: switch.outdoor_lights
- id: '1547241126929'
  alias: Everyones home
  trigger:
  - entity_id: group.adults
    from: not_home
    platform: state
    to: home
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - after: sunset
    condition: sun
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id: switch.outdoor_lights
- id: '1547328859557'
  alias: Someone left after dark
  trigger:
  - entity_id: group.adults
    for:
      hours: 0
      minutes: 15
      seconds: 0
    from: home
    platform: state
    to: not_home
  condition:
  - after: sunset
    condition: sun
  action:
  - data: {}
    service: switch.turn_on
    target:
      entity_id: switch.outdoor_lights
- id: '1547432270277'
  alias: Workday Mornings - Turn on Kitchen Light
  trigger:
  - at: 06:15:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data: {}
    service: switch.turn_on
    target:
      entity_id: switch.kitchen_light_switch
  mode: single
- id: '1547433263483'
  alias: Workday Mornings - Turn on Outdoor Lights
  trigger:
  - at: 06:00:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - before: sunrise
    condition: sun
  action:
  - data: {}
    service: switch.turn_on
    target:
      entity_id: switch.outdoor_lights
  mode: single
- id: '1547434549041'
  alias: Sunrise - Turn Off Outdoor Lights
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id:
      - switch.outdoor_lights
- id: '1547435118208'
  alias: Workday Mornings - Turn off Kitchen Light
  trigger:
  - at: 08:20:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data: {}
    service: switch.turn_off
    target:
      entity_id:
      - switch.kitchen_light_switch
- id: '1648953669498'
  alias: UPS on battery
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ups_status
    attribute: friendly_name
    to: ONBATT
    from: ONLINE
  condition: []
  action:
  - service: notify.notify
    data:
      message: UPS on battery
  mode: single
- id: '1648953861359'
  alias: UPS off battery
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ups_status
    attribute: friendly_name
    to: ONLINE
    from: ONBATT
  condition: []
  action:
  - service: notify.notify
    data:
      message: UPS  off battery
  mode: single
- id: '1651675937641'
  alias: Turn on Kitchen Light when Garage door opens after sunset
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door_access_control
    to: 'on'
    from: 'off'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: 09ef56958255a9b2b8a3ce737b4b63dd
  mode: single
- id: '1652748926018'
  alias: Turn off Master Bedroom AC
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 02c74a710a384786aa620119f92aa7dd
    entity_id: remote.master_bedroom_tv
    domain: remote
  condition:
  - condition: time
    before: 00:00:00
    after: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: climate.turn_off
    data: {}
    target:
      device_id: ff90ae596fa8ecb3f3e7c5ae50eb72b9
  mode: single
- id: '1652749365472'
  alias: Turn on Master Bedroom AC
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 02c74a710a384786aa620119f92aa7dd
    entity_id: remote.master_bedroom_tv
    domain: remote
  condition:
  - condition: time
    before: 00:00:00
    after: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: numeric_state
    entity_id: climate.d828c9202173_climate
    attribute: current_temperature
    above: '70'
  action:
  - service: climate.turn_on
    data: {}
    target:
      device_id: ff90ae596fa8ecb3f3e7c5ae50eb72b9
  mode: single
